### ISSUE TITLE
Please publish source code

### ISSUE THREAD

**Issue by dduenker** [TWiStErRob/net.twisterrob.inventory#171]
Hello Róbert,

today i found your app after failing to find a free app fitting my requirements.
Your app is quite nice, while the most interesting open issues for me are translations and barcode scanning.
Now i am not the only one living in my home and others are quite vocal about free software and don't want me to inventorize our home without being sure, that no copies of the data are stored elsewhere.
Is there any possibility, that you will publish the source code to this app, so that it can be brought to the f-droid app store?
In there it would be without competition and you would broaden your user base towards free software enthusiasts, which might even help with the project in the future.

Thanks for this interesting project, i wish you all the best. :)

**Comment by danielinteractive** [comment]
+1 would be great to open source the code for this app, also to allow for faster development via community contributions.
